Wechall/additional
pwncollege/dojo pull request #217
Opened 2023-09-12 16:54 UTC by Zeeshan12340

basically, adding the extra stuff for wechall.net, global rank and user count, `global_scoreboard_data` is the same as `dojo_scoreboard_data` with arguments ignored and duration filter query removed so maybe it's not even needed. Other things worked fine for me and i tested for some edge cases but i obviously don't have the actual pwn.college dataset.

P.S: I don't know why these previous commits are still here.

2023-09-14 18:24 UTC, ConnorNelson commented
So `ignore_visibility` actually has to do with visibility start/stop times. What we really want to do if we want official only, is `.filter_by(official=1)`. I'm also not completely sure what's going to happen when two official dojos share a challenge, but *probably* it will result in duplicated solves in this query. I think we need some sort of `.distinct(Solves.challenge_id)` or something like that before we group.

2023-09-14 19:51 UTC, Zeeshan12340 commented
Whoops, completely misread what `ignore_visibility` was doing. `DojoChallenges.solves().filter(Dojos.official == 1).distinct(Solves.challenge_id)`  seems like it filters for the official dojos correctly. I'll have to test the `distinct ` query because I do not have dojos that share challenges setup.

2023-10-05 18:07 UTC, ConnorNelson commented on dojo_plugin/api/v1/score.py
> +        user_count = len(Users.query.all())
Can we do `Users.query.count()`

```
In [77]: %time Users.query.count()
CPU times: user 4.96 ms, sys: 66 µs, total: 5.02 ms
Wall time: 18.7 ms
Out[77]: 38869

In [78]: %time len(Users.query.all())
CPU times: user 5.13 s, sys: 281 ms, total: 5.41 s
Wall time: 5.42 s
Out[78]: 38869
```

2023-10-05 18:07 UTC, ConnorNelson requested changes
Happy to merge with this simple change. Thanks!

2023-10-05 18:10 UTC, Zeeshan12340 commented on dojo_plugin/api/v1/score.py
> +        user_count = len(Users.query.all())
Done!

2023-10-05 18:26 UTC, merged